RedZoneCatsVideoDatabase/Controllers/CatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RedZoneCatsVideoDatabase;

namespace RedZoneCatsVideoDatabase.Controllers
{
    public class CatsController : Controller
    {
        private RedZoneCatsVideoEntities db = new RedZoneCatsVideoEntities();

        // GET: Cats
        public ActionResult Index()
        {
            return View(db.Cats.ToList());
        }

        // GET: Cats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cat cat = db.Cats.Find(id);
            if (cat == null)
            {
                return HttpNotFound();
            }
            return View(cat);
        }

        // GET: Cats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,breed,sex,age")] Cat cat)
        {
            if (ModelState.IsValid)
            {
                db.Cats.Add(cat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cat);
        }

        // GET: Cats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cat cat = db.Cats.Find(id);
            if (cat == null)
            {
                return HttpNotFound();
            }
            return View(cat);
        }

        // POST: Cats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,breed,sex,age")] Cat cat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cat);
        }

        // GET: Cats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cat cat = db.Cats.Find(id);
            if (cat == null)
            {
                return HttpNotFound();
            }
            return View(cat);
        }

        // POST: Cats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cat cat = db.Cats.Find(id);
            List<Video_Cat_Junction> videos = (from v in db.Video_Cat_Junction
                                             where v.cat_id == id
                                             select v).ToList();
            foreach (Video_Cat_Junction v in videos)
            {
                db.Video_Cat_Junction.Remove(v);
            }
            db.Cats.Remove(cat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RedZoneCatsVideoDatabase/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using RedZoneCatsVideoDatabase;
using RedZoneCatsVideoDatabase.Models;

namespace RedZoneCatsVideoDatabase.Controllers
{
    public class VideosController : Controller
    {
        private RedZoneCatsVideoEntities db = new RedZoneCatsVideoEntities();

        // GET: Videos
        public ActionResult Index()
        {
            List<VideoSearchViewModel> vids = (from v in db.Videos
                                               select new VideoSearchViewModel
                                               {
                                                   id = v.id,
                                                   name = v.name,
                                                   location = v.location,
                                                   contentType = v.contentType
                                               }).ToList();

            populateLists();

            return View(vids);
        }

        [HttpPost]
        public ActionResult Index(VideoSearchViewModel search)
        {
            List<VideoSearchViewModel> vids = (from v in db.Videos
                                               where (v.name.ToLower().Contains(search.name.ToLower() ?? v.name.ToLower()))
                                               && (v.location.ToLower().Contains(search.location.ToLower() ?? v.location.ToLower()))
                                               select new VideoSearchViewModel
                                               {
                                                   id = v.id,
                                                   name = v.name,
                                                   location = v.location,
                                                   contentType = v.contentType
                                               }).ToList();

            search.catList.Remove(0);
            List<int> catId = (from c in db.Cats
                               where (c.sex.ToLower().Contains(search.catSex))
                               || (c.age.Contains(search.catAge))
                               select c.id).ToList();

            search.catList = search.catList.Concat(catId).ToList();

            if (search.catBreed.Count() > 0)
            {
                catId = (from c in db.Cats
                         where search.catBreed.Contains(c.breed)
                         select c.id).ToList();
                search.catList = search.catList.Concat(catId).ToList();
            }

            if (search.catList.Count() > 0)
            {
                List<int> catVideoId = (from j in db.Video_Cat_Junction
                                        where search.catList.Contains(j.cat_id)
                                        select j.video_id).ToList();
                vids = (from v in vids
                        where catVideoId.Contains(v.id)
                        select v).ToList();
            }


            populateLists();
            return View(vids);
        }



        // GET: Videos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Video video = (from v in db.Videos
            //               where v.id == id
            //               select new
            //               {
            //                   id = v.id,
            //                   name = v.name,
            //                   location = v.location,
            //                   contentType = v.contentType
            //               }).ToList()
            //               .Select(v => new Video
            //               {
            //                   id = v.id,
            //                   name = v.name,
            //                   location = v.location,
            //                   contentType = v.contentType
            //               }).FirstOrDefault();

            VideoDetailsViewModel video = (from v in db.Videos
                                           where v.id == id
                                           select new VideoDetailsViewModel
                                           {
                                               id = v.id,
                                               name = v.name,
                                               location = v.location,
                                               contentType = v.contentType
                                           }).FirstOrDefault();

            if (video == null)
            {
                return HttpNotFound();
            }

            video.catList = (from j in db.Video_Cat_Junction
                             where j.video_id == id
                             select j.cat_id).ToList();

            video.catNames = new List<string>();
            foreach (int catId in video.catList)
            {
                string catName = (from c in db.Cats
                                  where c.id == catId
                                  select c.name).FirstOrDefault();
                video.catNames.Add(catName);
            }

            //Video video = db.Videos.Find(id);

            return View(video);
        }

        public FileResult DownloadFile(int? id)
        {
            byte[] bytes;
            string fileName, contentType;

            Video video = (from v in db.Videos
                           where v.id == id
                           select v).FirstOrDefault();

            bytes = video.data;
            contentType = video.contentType.ToString();
            fileName = video.name.ToString() + "." + contentType.Split('/')[1];

            return File(bytes, contentType, fileName);
        }

        // GET: Videos/Create
        public ActionResult Create()
        {
            populateLists();
            return View();
        }

        // POST: Videos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VideoUploadViewModel video)
        {
            if (ModelState.IsValid)
            {
                foreach (HttpPostedFileBase file in video.Files)
                {
                    byte[] bytes;
                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        bytes = br.ReadBytes(file.ContentLength);
                    }

                    Video v = new Video
                    {
                        name = video.name,
                        location = video.location,
                        data = bytes,
                        contentType = file.ContentType
                    };

                    if (video.catList.Count() > 0)
                    {
                        foreach (int catId in video.catList)
                        {
                            Cat c = db.Cats.Find(catId);
                            Video_Cat_Junction catVideo = new Video_Cat_Junction
                            {
                                video_id = v.id,
                                cat_id = catId
                            };
                            db.Video_Cat_Junction.Add(catVideo);
                        }
                    };

                    db.Videos.Add(v);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            return View(video);
        }

        public JsonResult VideoUpload(VideoUploadViewModel video)
        {
            if (ModelState.IsValid)
            {

                byte[] bytes;
                using (BinaryReader br = new BinaryReader(video.Files[0].InputStream))
                {
                    bytes = br.ReadBytes(video.Files[0].ContentLength);
                }

                Video v = new Video
                {
                    name = video.name,
                    location = video.location,
                    data = bytes,
                    contentType = video.Files[0].ContentType
                };

                if (video.catList.Count() > 0)
                {
                    foreach (int catId in video.catList)
                    {
                        Cat c = db.Cats.Find(catId);
                        Video_Cat_Junction catVideo = new Video_Cat_Junction
                        {
                            video_id = v.id,
                            cat_id = catId
                        };
                        db.Video_Cat_Junction.Add(catVideo);
                    }
                };

                db.Videos.Add(v);
                db.SaveChanges();
                return Json("success", JsonRequestBehavior.DenyGet);
            }

            return Json("failed", JsonRequestBehavior.DenyGet);
        }

        // GET: Videos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Video video = db.Videos.Find(id);
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // POST: Videos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,location")] Video video)
        {
            if (ModelState.IsValid)
            {

RedZoneCatsVideoDatabase/Views/Videos/Create.cshtml
@model RedZoneCatsVideoDatabase.Models.VideoUploadViewModel

@{
    ViewBag.Title = "Create";
}



<h2>Create</h2>

@using (Html.BeginForm("VideoUpload", "Videos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Video</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.catList, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.catList, ViewBag.CatList as MultiSelectList, new { size = 10 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Files, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Files, new { type = "file", name = "Files", multiple = "true" })
                @Html.ValidationMessageFor(model => model.Files, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<p id="fileUploadCounter"></p>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<style type="text/css">
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $(document).ready(function () {
        $('form').submit(function (event) {
            var filelist = this[4].files;
            var minFiles = 0;
            var maxFiles = filelist.length;
            document.getElementById("fileUploadCounter").innerHTML = minFiles + " of " + maxFiles + " files uploaded"
            for (var key = 0; key < maxFiles; key++) {
                var formdata = new FormData();
                formdata.append("name", $('input[name=name]').val());
                formdata.append("location", $('input[name=location').val());
                formdata.append("catList", $('select[name=catList]').val());
                formdata.append("Files", filelist[key]);

                $.ajax({
                    type: "POST",
                    url: "/Videos/VideoUpload",
                    data: formdata,
                    dataType: "json",
                    encode: true,
                    contentType: false,
                    processData: false,
                    async: false,
                    success: function (e) {
                        if (e = "success") {
                            minFiles++;
                            document.getElementById("fileUploadCounter").innerHTML = minFiles + " of " + maxFiles + " files uploaded"
                        }
                        else if (e = "failed")
                        {
                            alert("Upload Failed");
                            minFiles++;
                            document.getElementById("fileUploadCounter").innerHTML = minFiles + " of " + maxFiles + " files uploaded"
                        }
                    }
                })
            };
            document.getElementById("fileUploadCounter").innerHTML = "All files finished uploading."
            event.preventDefault();
        });
    });

</script>

RedZoneCatsVideoDatabase/Views/Videos/Delete.cshtml
@model RedZoneCatsVideoDatabase.Models.VideoDetailsViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Video</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contentType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RedZoneCatsVideoDatabase/Views/Videos/Details.cshtml
@model RedZoneCatsVideoDatabase.Models.VideoDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Video</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.data)
        </dt>

        <dd>
            @Html.ActionLink("Download File", "DownloadFile", new { id = Model.id})
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contentType)
        </dd>

        <dt>
            Cats
        </dt>

        <dd>
            @for (var i = 0; i < Model.catList.Count(); i++)
            {
                @Html.ActionLink(Model.catNames[i], "Details", "Cats", new { id = Model.catList[i]}, new { })<br />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RedZoneCatsVideoDatabase/Views/Videos/Edit.cshtml
@model RedZoneCatsVideoDatabase.Video

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Videos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Video</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RedZoneCatsVideoDatabase/Views/Videos/Index.cshtml
@model IEnumerable<RedZoneCatsVideoDatabase.Models.VideoSearchViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <td>
            <button onclick="toggleSearch()" align="left" class="col-md-2">Search</button>
        </td>
        <td>
            <p align="right" class="col-md-2">@Html.ActionLink("Create New", "Create")</p>
        </td>
    </tr>
</table>

@using (Html.BeginForm("Index", "Videos", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" id="search-block" style="display: none">
        <h4>Search</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.FirstOrDefault().name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstOrDefault().name, new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.FirstOrDefault().name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstOrDefault().location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstOrDefault().location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstOrDefault().location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstOrDefault().catList, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FirstOrDefault().catList, ViewBag.Catlist as MultiSelectList, new { size = 10, multiple = true })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstOrDefault().catBreed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.FirstOrDefault().catBreed, ViewBag.CatBreeds as MultiSelectList, new { size = 10 })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstOrDefault().catSex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstOrDefault().catSex, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstOrDefault().catSex, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstOrDefault().catAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstOrDefault().catAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstOrDefault().catAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Location
        </th>
        <th>
            ContentType
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contentType)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

<script type="text/javascript">
    var searchHidden = true;
    function toggleSearch() {
        if (searchHidden) {
            document.getElementById('search-block').style.display = "block";
            searchHidden = false;
        }
        else {
            document.getElementById('search-block').style.display = "none";
            searchHidden = true;
        }
    };
    $(document).ready(function () {
        $('input[name=name]').val("")
        $('input[name=location]').val("")
        $('option[selected=selected]').removeAttr("selected")
    });
</script>